### ISSUE TITLE
Server list down

### ISSUE THREAD

**Issue by ayunami2000** [BK-TN/Sanicball#29]
The server list (and all of bdgr.zone) is down. If the site is not going to be running anymore, can you send the last known server list? Thanks!

**Comment by ViciousBadger** [comment]
The list is down because I can no longer host @ bdgr.zone for free. I have recently moved to a new apartment and my internet provider wants a fee for setting up a static IP address. It's not expensive but I think this is a good time to drop my last bit of involvement in this game. I know it's inconvenient but I hoped some tech savvy player would take over the hosting job and notify his peers. After all there is a setting in the game to change the URL to get servers from.

**Comment by ayunami2000** [comment]
I might be able to host the server list myself, actually. I should be able to use my AlwaysData account for it. If you could send the current list of servers that would be a huge help!

**Comment by ViciousBadger** [comment]
The server list (source code here: https://github.com/BK-TN/SanicballServerList) was dynamically generated and servers had to push their IP to the list every 5 minutes. If they failed to do so they would be removed. This means the sever browser only contains the IPs of servers that were online in the last few minutes before the list went offline. These IPs are:
```
45.157.190.160:25000
fjupps.sytes.net:25000
85.214.121.178:25000
```

**Comment by ayunami2000** [comment]
Alright, thank you so much! I'll see if I can host this server list myself and if so I will update this with the link.

**Comment by ayunami2000** [comment]
Ok, I have set up a new server list on pythonanywhere: http://ayunami2000.pythonanywhere.com (It took a while to figure out how django and wsgi and everything worked, but it seems to be functional now!) I also added in some regex to prevent xss.

**Comment by ViciousBadger** [comment]
I can redirect the sanicball.bdgr.zone/servers url to point at your url if that's ok? I still own the domain and it's getting a bit sad that noone can see any servers

**Comment by ayunami2000** [comment]
Sure, that would work! Thanks so much!

**Comment by ViciousBadger** [comment]
Hi, I have set up the redirect now, however for some reason it does not work right now. When it worked a few days ago it pointed to:
http://ayunami2000.pythonanywhere.com/servers
.. unfortunately your server wont listen to this url unless you tweak the code a little - in the file `urls.py` replace:
```
    path('', views.list, name="list"),
    path('add/', views.add, name="add"),
```
with:
```
    path('servers/', views.list, name="list"),
    path('servers/add/', views.add, name="add"),
```

**Comment by ayunami2000** [comment]
Ok, done! I have actually done this instead to keep compatibility with just putting in the URL alone. Will this work or do I need to do something else?
![image](https://user-images.githubusercontent.com/24785136/146294767-5cf471b7-39f2-4d48-a5f0-d920467277b3.png)


edit: I made it this since it wasn't redirecting with the / at the end from your site:
![image](https://user-images.githubusercontent.com/24785136/146294942-7752f84f-2cd9-48ff-a2f8-ca928493b6c3.png)

**Comment by ayunami2000** [comment]
Also your server list does not redirect over https which is a problem because I believe sanicball uses https://... by default for the server URL.
