### ISSUE TITLE
End of Race Bug

### ISSUE THREAD

**Issue by tanuki-billie** [BK-TN/Sanicball#5]
For some reason, when the race ends, you can't be killed by anything (falling off the platform in Rainbow Road, the water in Green Hill, the lava in Flame Core). This is especially noticeable with Super Sanic, where his sheer speed is so fast that he really can't be stopped.

**Comment by BK-TN** [comment]
Acknowledged! Probably not that hard to fix

**Comment by BK-TN** [comment]
Welp, fixed it in like a minute
